### PR TITLE
fix CPF wall_clock offset precision constraint

### LINKED ISSUE #6423: xtrigger wall_clock offset trimmed to `cycle point format`
### Description

The xtrigger `wall_clock` offset is trimmed to precision of `cycle point format`

### Reproducible Example
```
[scheduler]
    cycle point format = CCYYMMDDThh
    allow implicit tasks = True
[scheduling]
    initial cycle point = 20241017T00
    [[xtriggers]]
        clock_PT25M = wall_clock(offset=PT25M):PT20S
    [[graph]]
        T-00 = """
@clock_PT25M => a
"""

[runtime]
    [[root]]
        script = sleep $((1 + $RANDOM % 10))
```
image

### Expected Behaviour

The `wall_clock` offset should not be restricted by the cycle point precision

image

### PR DESCRIPTION
**Pull request by dwsutherland**
closes #6423 

```
[scheduler]
    cycle point format = CCYYMMDDThh
    allow implicit tasks = True
[scheduling]
    initial cycle point = 20241017T22
    [[xtriggers]]
        clock_PT25M31S = wall_clock(offset=PT25M31S):PT20S
    [[graph]]
        T-00 = """
@clock_PT25M31S => a
"""
[runtime]
    [[root]]
        script = sleep $((1 + $RANDOM % 10))
```

image

**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` (and `conda-environment.yml` if present).
- [x] Tests added.
- [x] Changelog entry included if this is a change that can affect users
- [x] If this is a bug fix, PR should be raised against the relevant `?.?.x` branch.

### CODE REVIEW

**Comment by hjoliver** [comment]
>  [x] Existing tests cover.

Presumably not, as we've been living with the bug?

**Comment by dwsutherland** [comment]
> > [x] Existing tests cover.
> 
> Presumably not, as we've been living with the bug?

Well coverage is 100%, and trigger offsets are tested ... But I could add a test that has CPF at lower resolution than offset

**Comment by hjoliver** [comment]
Yeah worth doing that I think.

**Comment by dwsutherland** [comment]
> Yeah worth doing that I think.

Good thing I tried.. Found a way to break my solution, and have been working on various solutions all afternoon..
Will have it up by this evening.

File: changes.d/6431.fix.md [hunk 1]
```diff
@@ -0,0 +1 @@
+The `cycle point format` was imposing an undesirable constraint on `wall_clock` offsets, this has been fixed.
```
Comment (oliver-sanders) [inline changes.d/6431.fix.md:1]:
```suggestion
Allowed `wall_clock` offsets to use smaller precision than the `cycle point format` (e.g. `wall_clock(offset="PT1M")` in combination with `cycle point format = CCYY`).
```

Comment (dwsutherland) [reply changes.d/6431.fix.md:1]: Well technically they were capable of it before, but some change broke it.

File: cylc/flow/task_proxy.py [hunk 2]
```diff
@@ -424,14 +423,20 @@ def get_clock_trigger_time(
...
-            offset = int(
-                point_parse(str(trigger_time)).seconds_since_unix_epoch)
-            self.clock_trigger_times[offset_str] = offset
+                trigger_time = (
+                    point_parse(
+                        point_time.__str__(strftime_format='%Y%m%dT%H%M%S'),
+                        '%Y%m%dT%H%M%S'
+                    )
+                    + interval_parse(offset_str)
+                )
```
Comment (MetRonnie) [inline cylc/flow/task_proxy.py:436]: There is no need to mess with the strftime_format:
```suggestion
            # Convert ISO8601Point into metomi-isodatetime TimePoint at full
            # second precision (N.B. it still dumps at the same precision
            # as workflow cycle point format):
            point_time = point_parse(str(point))
            if offset_str == 'P0Y':
                trigger_time = point_time
            else:
                trigger_time = point_time + interval_parse(offset_str)
```

File: cylc/flow/cycling/iso8601.py
Comment (MetRonnie) [inline cylc/flow/cycling/iso8601.py:1]: There is no need to change this file actually, see above comment

**Review by MetRonnie — CHANGES_REQUESTED** [review]
Tested 👍 Can actually be even simpler

File: cylc/flow/task_proxy.py (hunk 2 above)
Comment (dwsutherland) [reply cylc/flow/task_proxy.py:436]: No way! shocking .. Just tested this and it worked..

Ah I think I know what the issue was ... I was originally converting these objects back to `ISO8601Point` and `ISO8601Interval` adding them together then parsing them again but you get a dump format  and epoc seconds the same as the CPF (trimmed to that precision)...
i.e. if you have `CCYY-MM-DD` the addition will trim off the minutes and seconds.. Hence why I returned a new object with `%Y%m%dT%H%M%S` precision.

And as the TimePoint and Duration objects also have a dump format I assumed they behaved the same. Doh!

Reverting things to this.. Thanks

File: cylc/flow/cycling/iso8601.py
Comment (dwsutherland) [reply cylc/flow/cycling/iso8601.py:1]: Noted above!

File: cylc/flow/task_proxy.py (hunk 2 above)
Comment (dwsutherland) [reply cylc/flow/task_proxy.py]: (p.s. sorry, should have merged yours in first then rebased)

**Review by hjoliver — APPROVED** [review]

File: changes.d/6431.fix.md (hunk 1 above)
Comment (hjoliver) [reply changes.d/6431.fix.md:1]: Approved, but I prefer @oliver-sanders wording here, in terms of clarity for users.

File: cylc/flow/task_proxy.py (hunk 2 above)
Comment (MetRonnie) [reply cylc/flow/task_proxy.py]: Yeah I stuck a breakpoint in there and got confused by the dump format precision for a while 😄 Hopefully the comment I included makes it clear for people debugging in the future

**Review by MetRonnie — APPROVED** [review]
