### PR TITLE
Test the simulation mode code.

### LINKED ISSUE #5654: Test Simulation Mode
## Synopsis

Simulation Mode is currently largely untested. To ensure that https://github.com/cylc/cylc-flow/issues/5641 doesn't break existing interfaces I intend to write a thorough set of tests for similar existing functionality. This ticket is a way of keeping notes about what I need to test.

Although the target of the work in #5641  is a new feature, fixing testing for existing features should be counted as a bug-fix, hence the 8.2.1 milestone.

## Current state of play

There are functional tests in `tests/f/modes` for dummy mode, but not for simulation mode, at least on the surface. On closer insepection it looks like they rely on settings in `[runtime][namespace]simulation` which describes itself as 

> task configuration for workflow *simulation* and *dummy* run modes.

## What _should_ simulation mode do?

- [ ] Prevent a run directory being created for tasks.
- [ ] Take a time specified by:
  - [ ]  `[simulation]speedup factor` * `execution time limit` if both are set.
  - [ ]  else `[simulation]default run length`.
- [ ] Config item `time limit buffer` should not affect simulation mode (Docs claim that it is only used in dummy mode).
- [ ] Tasks should fail at cycle points specified by `[simulation]fail cycle points`.
- [ ] Tasks should fail on the first attempt, but not retries if `[simulation]fail try 1 only` set.
- [ ] Task event handers will only be called if `disable task event handlers` is set True.
- [ ]

### PR DESCRIPTION
**Pull request by wxtim**
Closes #5654 

Pre-requisite work for Skip mode 

- Refactor simulation mode functions.
- Improve documentation of sim mode settings.
- Ensure 100% test coverage of sim mode.

On an initial self-review I noticed that `configure_sim_modes` might as well be in the `simulation` module. I've moved it, but not squashed that commit down, because that way reviewers can see how I refactored it in a separate commit to the one I move it in.

**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` (and `conda-environment.yml` if present).
- [x] Tests are included (or explain why tests are not needed).
- [x] `CHANGES.md` entry included if this is a change that can affect users
- [x] [Cylc-Doc](https://github.com/cylc/cylc-doc) pull request opened if required at cylc/cylc-doc/pull/641.
- [x] If this is a bug fix, PR should be raised against the relevant `?.?.x` branch.

### CODE REVIEW

**Comment by wxtim** [comment]
Changed to draft because a final sanity check/attempt to write an example for the docs showed up at least 2 exciting bugs.

File: changes.d/5712.fix.md [hunk 1]
```diff
@@ -0,0 +1 @@
+Test the simulation mode code.
```
Comment (oliver-sanders) [inline changes.d/5712.fix.md:1]: not a user facing change.

File: cylc/flow/task_job_mgr.py [hunk 2]
```diff
@@ -1000,16 +1000,17 @@ def _simulation_submit_task_jobs(self, itasks, workflow):
             itask.waiting_on_job_prep = False
             itask.submit_num += 1
             self._set_retry_timers(itask)
-            itask.platform = {'name': 'SIMULATION'}
+            itask.platform['name'] = 'SIMULATION'
```
[the remark this answers is not in the document]
Comment (wxtim) [reply cylc/flow/task_job_mgr.py:1003]: We don't want the platform config in it's entirety replaced by `{'name': 'SIMULATION'}`. When we come around to retry with that config we have no info about the host &c to use. This is a bug!

File: cylc/flow/task_job_mgr.py [hunk 3]
```diff
@@ -1000,16 +1000,17 @@ def _simulation_submit_task_jobs(self, itasks, workflow):
...
             itask.summary['job_runner_name'] = 'SIMULATION'
             itask.summary[self.KEY_EXECUTE_TIME_LIMIT] = (
-                itask.tdef.rtconfig['job']['simulated run length']
+                itask.tdef.rtconfig['simulation']['simulated run length']
             )
             itask.jobs.append(
                 self.get_simulation_job_conf(itask, workflow)
             )
+            itask.state.status = TASK_STATUS_PREPARING
```
[the remark this answers is not in the document]
Comment (wxtim) [reply cylc/flow/task_job_mgr.py:1011]: Otherwise it sticks in the waiting state on retry.

File: tests/functional/modes/03-simulation.t [hunk 4]
```diff
@@ -0,0 +1,31 @@
...
+. "$(dirname "$0")/test_header"
+set_test_number 2
+
+install_workflow "${TEST_NAME_BASE}" "${TEST_NAME_BASE}"
+run_ok "${TEST_NAME_BASE}-validate" cylc validate "${WORKFLOW_NAME}"
+workflow_run_ok "${TEST_NAME_BASE}-run" \
+    cylc play \
+        --no-detach \
+        --mode=simulation \
+        --reference-test "${WORKFLOW_NAME}" 2> sim.log
```
[the remark this answers is not in the document]
Comment (wxtim) [reply tests/functional/modes/03-simulation.t:29]: No - it's the stub of an extra test I decided was overkill. Will Remove.

File: tests/integration/test_simulation.py [hunk 5]
```diff
@@ -0,0 +1,143 @@
...
+
+def test_false_if_not_running(sim_time_check_setup, monkeypatch):
+    schd, itasks, msg_q = sim_time_check_setup
+
+    # False if task status not running:
+    assert sim_time_check(msg_q, itasks) is False
+
+
+def test_sets_started_time(sim_time_check_setup, monkeypatch):
+    """But that the method still returns False"""
```
[the remark this answers is not in the document]
Comment (wxtim) [reply tests/integration/test_simulation.py:91]: I've refactored - the idea is to read the name of the test and the first line of the doc as complimentary clauses. 🤶🏼

File: cylc/flow/task_job_mgr.py (hunk 2 above)
[the remark this answers is not in the document]
Comment (oliver-sanders) [reply cylc/flow/task_job_mgr.py:1003]: I think this was correct before.

Sure this is modifying the `localhost` platform that each new `TaskProxy` object is (incorrectly) assigned when it is initiated?

File: cylc/flow/task_job_mgr.py [hunk 6]
```diff
@@ -1000,16 +1000,17 @@ def _simulation_submit_task_jobs(self, itasks, workflow):
             itask.waiting_on_job_prep = False
             itask.submit_num += 1
             self._set_retry_timers(itask)
-            itask.platform = {'name': 'SIMULATION'}
+            itask.platform['name'] = 'SIMULATION'
             itask.summary['job_runner_name'] = 'SIMULATION'
             itask.summary[self.KEY_EXECUTE_TIME_LIMIT] = (
-                itask.tdef.rtconfig['job']['simulated run length']
+                itask.tdef.rtconfig['simulation']['simulated run length']
```
[the remark this answers is not in the document]
Comment (oliver-sanders) [reply cylc/flow/task_job_mgr.py:1006]: I'm not sure this was wrong, because if it was then we would have got a `KerError` whenever this code was run, so `[job][simulated run length]` must have existed right?

File: cylc/flow/task_job_mgr.py (hunk 3 above)
[the remark this answers is not in the document]
Comment (oliver-sanders) [reply cylc/flow/task_job_mgr.py:1011]: This wasn't needed before right?

This gets done somewhere else.

File: tests/integration/test_simulation.py [hunk 7]
```diff
@@ -0,0 +1,143 @@
...
+
+class PrintLog():
+    def __init__(self):
+        self.old_records = []
+
+    def log(self, records):
+        for record in records:
+            if record not in self.old_records:
+                print(record.message)
+                self.old_records.append(record)
```
[the remark this answers is not in the document]
Comment (oliver-sanders) [reply tests/integration/test_simulation.py]: (unresolved, still appears to be unused)

File: cylc/flow/simulation.py [hunk 8]
```diff
@@ -0,0 +1,220 @@
...
+    rtc: Dict[str, Any]
+) -> None:
+    """Force platform = localhost
+
+    Remove legacy sections [job] and [remote], which would conflict
+    with setting platforms.
+
+    TODO (Cylc 9): This function can probably be removed
+    when the items in FORBIDDEN_WITH_PLATFORM with platforms
+    are removed from the config - it will become trivially simple.
```
Comment (oliver-sanders) [inline cylc/flow/simulation.py:125]:
```suggestion
    This can be removed when support for the FORBIDDEN_WITH_PLATFORM
    configurations is dropped.
```

File: cylc/flow/task_job_mgr.py (hunk 6 above)
[the remark this answers is not in the document]
Comment (wxtim) [reply cylc/flow/task_job_mgr.py:1006]: Simulated run length isn't in the config spec. AFAICT Cylc just uses it as a convenient place to dump this value. We could make it part of an object on the scheduler if you want? Like `sim_mode_manager`

File: cylc/flow/task_job_mgr.py (hunk 3 above)
[the remark this answers is not in the document]
Comment (wxtim) [reply cylc/flow/task_job_mgr.py:1011]: Before what? No, resubmit was broken!

File: cylc/flow/simulation.py [hunk 9]
```diff
@@ -0,0 +1,220 @@
...
+        ).get_seconds()
+
+    return sleep_sec
+
+
+def build_simulation_script(rtc: Dict[str, Any], sleep_sec: int) -> str:
+    """Create fake scripting for simulation modes.
+
+    This is for Dummy mode only.
+    """
```
[the remark this answers is not in the document]
Comment (wxtim) [reply cylc/flow/simulation.py:101]: Probably not great terminology - willfix.

File: cylc/flow/task_job_mgr.py (hunk 3 above)
[the remark this answers is not in the document]
Comment (oliver-sanders) [reply cylc/flow/task_job_mgr.py:1011]: At the moment (master), I don't think that simulated jobs even go through the preparing state in the first place (which makes sense), we send them straight to submitted:

https://github.com/cylc/cylc-flow/blob/63ceffb21badc2d634a43241ae9a4da75e24189d/cylc/flow/task_job_mgr.py#L997-L1013

I don't think we should change this.

File: cylc/flow/task_job_mgr.py (hunk 6 above)
[the remark this answers is not in the document]
Comment (oliver-sanders) [reply cylc/flow/task_job_mgr.py:1006]: My point is that this appears to have been working before (otherwise we would have got traceback right?) so I'm not sure why it has changed here?

[the remark this answers is not in the document]
Comment (wxtim) [reply cylc/flow/task_job_mgr.py:1006]: > Did you change the output of the config stuff to move this from job to simulation?

No!

File: cylc/flow/task_job_mgr.py (hunk 2 above)
[the remark this answers is not in the document]
Comment (wxtim) [reply cylc/flow/task_job_mgr.py]: It does however, need the platform default for `submission retry delays` added to this "platform" to prevent a failure in `_set_retry_timers`  on the retry.

File: cylc/flow/task_job_mgr.py (hunk 3 above)
[the remark this answers is not in the document]
Comment (wxtim) [reply cylc/flow/task_job_mgr.py:1011]: At the moment on master the line

```python
            self.task_events_mgr.process_message(
                itask, INFO, TASK_OUTPUT_SUBMITTED
            )
```
just below this chunk converts a task in the waiting state to a task in the running state on the first pass, but doesn't on retry - so that sim mode hangs in waiting state. I'll find out more about why and get back to you.

File: cylc/flow/simulation.py [hunk 10]
```diff
@@ -0,0 +1,219 @@
...
+    now = time()
+    for itask in itasks:
+        if itask.state.status != TASK_STATUS_RUNNING:
+            continue
+        # Started time is not set on restart
+        if itask.summary['started_time'] is None:
+            itask.summary['started_time'] = now
+        timeout = (
+            itask.summary['started_time'] +
+            itask.tdef.rtconfig['simulation']['simulated run length']
```
Comment (wxtim) [inline cylc/flow/simulation.py:179]: Not a real config item, added to the `rtconfig['simulation']` dictionary at line 54.

File: cylc/flow/task_events_mgr.py [hunk 11]
```diff
@@ -591,6 +592,16 @@ def process_message(
                 itask, severity, message, event_time, flag, submit_num):
             return None
 
+        severity = cast(int, LOG_LEVELS.get(severity, INFO))
```
Comment (wxtim) [inline cylc/flow/task_events_mgr.py:595]: Moved out of `_process_message_check` because they only run if it is true.

File: cylc/flow/task_events_mgr.py [hunk 12]
```diff
@@ -777,24 +787,23 @@ def _process_message_check(
             return False
 
         if (
-                itask.state(TASK_STATUS_WAITING)
-                and
+            itask.state(TASK_STATUS_WAITING)
+            and itask.tdef.run_mode == 'live'   # Polling in live mode only.
```
Comment (wxtim) [inline cylc/flow/task_events_mgr.py:791]: The code within this section is designed to avoid problems with polling - but there will be no polling in simulation mode.

File: cylc/flow/task_job_mgr.py (hunk 3 above)
[the remark this answers is not in the document]
Comment (wxtim) [reply cylc/flow/task_job_mgr.py]: Closing this after in person convo with Oliver - taking a different approach to the resubmit problem.

**Comment by oliver-sanders** [comment]
> codecov/patch Successful in 1s — 100.00% of diff hit (target 95.00%) 

:tada:

File: tests/functional/modes/03-simulation.t [hunk 13]
```diff
@@ -0,0 +1,31 @@
...
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
+
+# Test that simulation mode runs, and reruns a failed task successfully.
```
Comment (oliver-sanders) [inline tests/functional/modes/03-simulation.t:18]:
```suggestion
# Test that simulation mode runs, and reruns a failed task successfully
# when execution retry delays is configured
```

**Review by oliver-sanders — APPROVED** [review]

**Review by MetRonnie — COMMENTED** [review]
Partial review

File: cylc/flow/task_events_mgr.py (hunk 11 above)
Comment (wxtim) [reply cylc/flow/task_events_mgr.py:595]: It's not meant to change anything.

File: cylc/flow/simulation.py [hunk 14]
```diff
@@ -0,0 +1,219 @@
...
+
+from queue import Queue
+from typing import Any, Dict, List, Optional, Union
+from time import time
+
+from cylc.flow.cycling import PointBase
+from cylc.flow.cycling.loader import get_point
+from cylc.flow.network.resolvers import TaskMsg
+from cylc.flow.platforms import FORBIDDEN_WITH_PLATFORM
+from cylc.flow.task_proxy import TaskProxy
```
[the remark this answers is not in the document]
Comment (wxtim) [reply cylc/flow/simulation.py:27]: #WellThatsHorrid

File: cylc/flow/task_events_mgr.py (hunk 11 above)
Comment (MetRonnie) [reply cylc/flow/task_events_mgr.py:595]: What did you mean by this then:

> Moved out of `_process_message_check` because they only run if it is true.

Comment (wxtim) [reply cylc/flow/task_events_mgr.py:595]: It only runs in `process_message_check` if that method is going to return true. Here it only runs after process message check returns true and not otherwise. I thought it was more helpful to understanding the flow of the program here.

Comment (wxtim) [reply cylc/flow/task_events_mgr.py]: Turns out you were right - I shouldn't have moved this. I was wrong to thing that `event_time` in process_event == `timestamp` in process message check and a couple of tests were broken by this. Please hit resolve if you are satisfied.

File: tests/unit/test_config.py [hunk 15]
```diff
@@ -1741,3 +1743,32 @@ def test_cylc_env_at_parsing(
...
+        'fail cycle points': '',
+    }
+    rtconfig_1 = {
+        'execution time limit': '',
+        'simulation': sim_section,
+        'job': job_section,
+        'outputs': {},
+    }
+    rtconfig_2 = deepcopy(rtconfig_1)
+    rtconfig_2['job'] = job_section
```
Comment (MetRonnie) [inline tests/unit/test_config.py:1764]: (Not needed)
```suggestion
```

File: tests/unit/test_simulation.py [hunk 16]
```diff
@@ -0,0 +1,172 @@
...
+    result = build_dummy_script(rtc, 60)
+    expect = [
+        'sleep 60',
+        "cylc message '1'",
+        "cylc message '2'",
+        f"cylc__job__dummy_result {str(fail_one_time_only).lower()}"
+        " 1 || exit 1"
+    ]
+    for i, line in enumerate(result.split('\n')):
+        assert expect[i] == line
```
Comment (MetRonnie) [inline tests/unit/test_simulation.py:78]:
```suggestion
    assert result.split('\n') == [
        'sleep 60',
        "cylc message '1'",
        "cylc message '2'",
        f"cylc__job__dummy_result {str(fail_one_time_only).lower()}"
        " 1 || exit 1"
    ]
```
This is easier to debug IMO

File: tests/unit/test_simulation.py [hunk 17]
```diff
@@ -0,0 +1,172 @@
...
+    """
+    disable_platforms(rtc)
+    assert rtc['platform'] == expect
+    subdicts = [v for v in rtc.values() if isinstance(v, dict)]
+    for val in [
+        v for subdict in subdicts
+        for k, v in subdict.items()
+        if k != 'platform'
+    ]:
+        assert val is None
```
Comment (MetRonnie) [inline tests/unit/test_simulation.py:100]:
```suggestion
    for subdict in subdicts:
        for k, val in subdict.items():
            if k != 'platform':
                assert val is None
```

File: cylc/flow/simulation.py [hunk 18]
```diff
@@ -0,0 +1,219 @@
...
+    for section, keys in FORBIDDEN_WITH_PLATFORM.items():
+        if section in rtc:
+            for key in keys:
+                if key in rtc[section]:
+                    rtc[section][key] = None
+    rtc['platform'] = 'localhost'
+
+
+def parse_fail_cycle_points(
+    f_pts_orig: list
```
Comment (MetRonnie) [inline cylc/flow/simulation.py:135]:
```suggestion
    f_pts_orig: List[str]
```

File: tests/unit/test_simulation.py [hunk 19]
```diff
@@ -0,0 +1,172 @@
...
+
+
+def test_parse_fail_cycle_points(monkeypatch):
+    before = ['2']
+    monkeypatch.setattr(
+        'cylc.flow.cycling.loader.get_point_cls',
+        lambda cycling_type: IntegerPoint)
+    result = parse_fail_cycle_points(before)[0]
+    assert isinstance(result, IntegerPoint)
+    assert int(result) == 2
```
Comment (MetRonnie) [inline tests/unit/test_simulation.py:110]:
```suggestion
def test_parse_fail_cycle_points(set_cycling_type):
    before = ['2', '4']
    set_cycling_type()
    assert parse_fail_cycle_points(before) == [
        IntegerPoint(i) for i in before
    ]
```

**Comment by wxtim** [comment]
@oliver-sanders  - accidentally re-tagged you for review. Happy for you to re-approve

**Review by MetRonnie — APPROVED** [review]

File: cylc/flow/task_job_mgr.py [hunk 20]
```diff
@@ -1002,14 +1002,7 @@ def _simulation_submit_task_jobs(self, itasks, workflow):
...
 
-            # We largely want a clean "platform" and not localhost,
-            # but we need to get the existing submission retry delays
-            # to stop _set_retry_delays missing it on retry.
-            itask.platform = {
-                'name': 'SIMULATION',
-                'submission retry delays':
-                    itask.platform['submission retry delays']
-            }
+            itask.platform = {'name': 'SIMULATION'}
```
Comment (oliver-sanders) [inline cylc/flow/task_job_mgr.py:1004]: I thought this was needed for submission retry delays?

**Comment by MetRonnie** [comment]
While you're here Tim, could you check that restarting a workflow that has been running in simulation mode will restart it in simulation mode? (If get round to testing it I'll comment below)

File: cylc/flow/task_job_mgr.py (hunk 20 above)
Comment (wxtim) [reply cylc/flow/task_job_mgr.py:1004]: https://github.com/cylc/cylc-flow/pull/5712#discussion_r1360622309

**Comment by wxtim** [comment]
> check that restarting a workflow that has been running in simulation mode will restart it in simulation mode without having to specify it? 

Yes, if you restart you do not have to specify mode to get the same mode.

> Oliver said trying to restart in simulation mode when it had been running in live mode merely restarted in live mode.

When I tried this on master it looks like it restarts in simulation mode (on master & my branch). Ick.

That's a bug.

File: cylc/flow/task_job_mgr.py (hunk 20 above)
Comment (oliver-sanders) [reply cylc/flow/task_job_mgr.py:1004]: You added `submission retry delays` here in an earlier commit, then removed them later.

Comment (oliver-sanders) [reply cylc/flow/task_job_mgr.py:1004]: See this: https://github.com/cylc/cylc-flow/pull/5712#discussion_r1322582113

Comment (wxtim) [reply cylc/flow/task_job_mgr.py:1004]: Are submission retry delays supposed to impact simulation mode?

No

    Can simulation tasks submit-fail?

No

Nor can I recreate the scenario where there was a problem. Have removed this.

**Comment by hjoliver** [comment]
This has two approvals, but I'm not sure if all questions addressed yet? If so, let's merge it.

**Comment by wxtim** [comment]
> This has two approvals, but I'm not sure if all questions addressed yet? If so, let's merge it.

Agreed, but I think @MetRonnie  or @oliver-sanders  should press the button here.

**Review by MetRonnie — APPROVED** [review]
Pending resolution of Oliver's comment

**Review by oliver-sanders — APPROVED** [review]
