### PR TITLE
Simplify and fix runahead computation.

### LINKED ISSUE #5825: reload: reloading shakes out runahead tasks
There's a nasty interaction between reload and runahead.

```ini
[scheduler]                    
    allow implicit tasks = True    
                               
[scheduling]                   
    initial cycle point = 2000
    runahead limit = P5D       
    [[graph]]                  
        P1D = """              
            a => b             
        """                    
                               
[runtime]                      
    [[root]]                   
        script = sleep 500 
```

When this workflow starts, the tasks 2000 through 2005 are submitted:

```
2023-11-17T10:05:39Z INFO - [2000/a submitted job:01 flows:1] => running
2023-11-17T10:05:39Z INFO - [2000/a running job:01 flows:1] health: execution timeout=None, polling intervals=PT1H,...
2023-11-17T10:05:39Z INFO - [2002/a submitted job:01 flows:1] => running
2023-11-17T10:05:39Z INFO - [2002/a running job:01 flows:1] health: execution timeout=None, polling intervals=PT1H,...
2023-11-17T10:05:39Z INFO - [2003/a submitted job:01 flows:1] => running
2023-11-17T10:05:39Z INFO - [2003/a running job:01 flows:1] health: execution timeout=None, polling intervals=PT1H,...
2023-11-17T10:05:39Z INFO - [2004/a submitted job:01 flows:1] => running
2023-11-17T10:05:39Z INFO - [2004/a running job:01 flows:1] health: execution timeout=None, polling intervals=PT1H,...
2023-11-17T10:05:39Z INFO - [2005/a submitted job:01 flows:1] => running
2023-11-17T10:05:39Z INFO - [2005/a running job:01 flows:1] health: execution timeout=None, polling intervals=PT1H,...
```

But if I reload it, the task 2006 submits:

```
2023-11-17T10:05:40Z INFO - Reloading task definitions.
2023-11-17T10:05:40Z INFO - [2000/a running job:01 flows:1] reloaded task definition
2023-11-17T10:05:40Z WARNING - [2000/a running job:01 flows:1] active with pre-reload settings
2023-11-17T10:05:40Z INFO - [2001/a running job:01 flows:1] reloaded task definition
2023-11-17T10:05:40Z WARNING - [2001/a running job:01 flows:1] active with pre-reload settings
2023-11-17T10:05:40Z INFO - [2002/a running job:01 flows:1] reloaded task definition
2023-11-17T10:05:40Z WARNING - [2002/a running job:01 flows:1] active with pre-reload settings
2023-11-17T10:05:40Z INFO - [2003/a running job:01 flows:1] reloaded task definition
2023-11-17T10:05:40Z WARNING - [2003/a running job:01 flows:1] active with pre-reload settings
2023-11-17T10:05:40Z INFO - [2004/a running job:01 flows:1] reloaded task definition
2023-11-17T10:05:40Z WARNING - [2004/a running job:01 flows:1] active with pre-reload settings
2023-11-17T10:05:40Z INFO - [2005/a running job:01 flows:1] reloaded task definition
2023-11-17T10:05:40Z WARNING - [2005/a running job:01 flows:1] active with pre-reload settings
2023-11-17T10:05:40Z INFO - [2006/a waiting(runahead) job:00 flows:1] reloaded task definition
2023-11-17T10:05:40Z INFO - LOADING job data
2023-11-17T10:05:40Z INFO - [2006/a waiting(runahead) job:00 flows:1] => waiting
2023-11-17T10:05:40Z INFO - [2006/a waiting job:00 flows:1] => waiting(queued)
```

Reload again and 2007 submits:

```
2023-11-17T10:05:45Z INFO - Reloading task definitions.
...
2023-11-17T10:05:45Z INFO - [2007/a waiting(runahead) job:00 flows:1] => waiting
2023-11-17T10:05:45Z INFO - [2007/a waiting job:00 flows:1] => waiting(queued)
2023-11-17T10:05:45Z INFO - Reload completed.
```

Reload again and 2008 submits:

```
2023-11-17T10:05:48Z INFO - Reloading task definitions.
...
2023-11-17T10:05:49Z INFO - [2008/a waiting(runahead) job:00 flows:1] => waiting
2023-11-17T10:05:49Z INFO - [2008/a waiting job:00 flows:1] => waiting(queued)
```

And so on.

### PR DESCRIPTION
**Pull request by hjoliver**
Fix [bug revealed on the forum](https://cylc.discourse.group/t/runahead-limit-not-respected/838/6): the runahead limit point erroneously advances when the limit is specified as a time interval and future triggers are present.

Taking a closer look at the code, I realized it still contained nasty vestiges of the old "max active cycle points" computation, when we were (or at least thought we were) counting active points, rather than all possible points, beyond the base point.  Probably my bad 😬 

It's considerably simpler and more efficient on this branch.

[UPDATE] close #5825

**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` (and `conda-environment.yml` if present).
- [x] Tests are included (or explain why tests are not needed).
- [x] `CHANGES.md` entry included if this is a change that can affect users
- [x] [Cylc-Doc](https://github.com/cylc/cylc-doc) pull request opened if required at cylc/cylc-doc/pull/XXXX.
- [x] If this is a bug fix, PR should be raised against the relevant `?.?.x` branch.

### CODE REVIEW

**Comment by oliver-sanders** [comment]
I think this might actually close #5825.

File: changes.d/5893.fix [hunk 1]
```diff
@@ -0,0 +1 @@
+Fixed bug in computing a time interval-based runahead limit when future triggers are present.
```
Comment (oliver-sanders) [inline changes.d/5893.fix:1]: \n

File: cylc/flow/task_pool.py [hunk 2]
```diff
@@ -318,73 +318,45 @@ def compute_runahead(self, force=False) -> bool:
...
+            # Find the earliest sequence point beyond the workflow start point.
+            points = [
+                point
+                for point in {
+                    seq.get_first_point(self.config.start_point)
+                    for seq in self.config.sequences
+                }
+                if point is not None
+            ]
+            base_point = min(points)
```
Comment (oliver-sanders) [inline cylc/flow/task_pool.py:334]: Look like the method only requires the `points` list to compute the minimum so no need to construct it:

```suggestion
            base_point = min(
                point
                for point in {
                    seq.get_first_point(self.config.start_point)
                    for seq in self.config.sequences
                }
                if point is not None
            )
```

File: cylc/flow/task_pool.py [hunk 3]
```diff
@@ -318,73 +318,45 @@ def compute_runahead(self, force=False) -> bool:
...
+                        TASK_STATUS_SUCCEEDED,
+                        TASK_STATUS_EXPIRED
+                    ) or (
+                        # For Cylc 7 back-compat, ignore incomplete tasks.
+                        # (Success is required in back-compat mode, so
+                        # failed tasks end up as incomplete; and Cylc 7
+                        # ignores failed tasks in computing the limit).
+                        itask.state.outputs.is_incomplete()
+                        and not cylc.flow.flags.cylc7_back_compat
                     )
```
Comment (oliver-sanders) [inline cylc/flow/task_pool.py:350]: The "Cylc 7 back-compat" comment is actually attached to the Cylc 8 logic.

Moreover, the Cylc 7 logic can interfere with the Cylc 8 logic because the `cylc.flow.flags.cylc7_back_compat` statement is only on one branch of the `or` (potential for future bugs?).

Would suggest either:

```python
if any(
    (
        not cylc.flow.flags.cylc7_back_compat
        and itask.state.outputs.is_incomplete()
    ) or (
        # For Cylc 7 back-compat, ignore incomplete tasks.
        # (Success is required in back-compat mode, so
        # failed tasks end up as incomplete; and Cylc 7
        # ignores failed tasks in computing the limit).
        cylc.flow.flags.cylc7_back_compat
        and not itask.state(
            TASK_STATUS_FAILED,
            TASK_STATUS_SUCCEEDED,
            TASK_STATUS_EXPIRED
        )
    )
    for itask in itasks
)
```

Or the more efficient:

```python
if cylc.flow.flags.cylc7_back_compat:
    if any(itask.state.outputs.is_incomplete() for itask in itasks)
else:
    # For Cylc 7 back-compat, ignore incomplete tasks.
    # (Success is required in back-compat mode, so
    # failed tasks end up as incomplete; and Cylc 7
    # ignores failed tasks in computing the limit).
    if any(
        not itask.state(
            TASK_STATUS_FAILED,
            TASK_STATUS_SUCCEEDED,
            TASK_STATUS_EXPIRED
        )
        for itask in itasks
    )
)
```

Comment (hjoliver) [reply cylc/flow/task_pool.py:350]: Good call.

File: tests/integration/test_task_pool.py [hunk 4]
```diff
@@ -1243,6 +1245,145 @@ async def test_detect_incomplete_tasks(
...
+                },
+            }
+        }
+        point = lambda point: IntegerPoint(str(int(point)))
+    else:
+        config = {
+            'scheduler': {
+                'allow implicit tasks': 'True',
+                'cycle point format': 'CCYY',
+                'cycle point time zone': 'Z'
```
Comment (hjoliver) [inline tests/integration/test_task_pool.py:1294]: Without `cycle point time zone = Z`, the second parameterized test fails (in my time zone at least) with:
```
FAILED tests/integration/test_task_pool.py::test_compute_runahead[datetime-normal-mode] - 
   cylc.flow.exceptions.SequenceDegenerateError:
      R/0001/P1Y, point format CCYY: equal adjacent points: 0001 => 000
```

but it passes if I run the exact same test individually 🤯

File: tests/integration/test_task_pool.py [hunk 5]
```diff
@@ -1243,6 +1245,145 @@ async def test_detect_incomplete_tasks(
...
+        # mark cycle 1 as incomplete (but finished)
+        schd.pool.get_task(point('0001'), 'a').state.reset(
+            TASK_STATUS_SUBMIT_FAILED
+        )
+
+        schd.pool.compute_runahead(force=True)
+
+        if compat_mode == 'compat-mode':
+            # Cylc 7 does not count failed tasks in runahead computation.
+            assert int(str(schd.pool.runahead_limit_point)) == 5
```
Comment (hjoliver) [inline tests/integration/test_task_pool.py:1339]: Different from your original version of the tes. Cylc 7 ignores failed tasks when computing the limit, that should include submit-failed.

File: tests/integration/test_task_pool.py [hunk 6]
```diff
@@ -1243,6 +1245,145 @@ async def test_detect_incomplete_tasks(
...
+        else:
+            # Cylc 8 does count failed tasks in runahead computation.
+            assert int(str(schd.pool.runahead_limit_point)) == 4  # no change
+
+        # mark cycle 1 as complete
+        # (via task message so the task gets removed before runahead compute)
```
Comment (hjoliver) [inline tests/integration/test_task_pool.py:1345]: The new extra-simplified method assumes completed tasks have been removed already, which doesn't happen if you artificially call `state_reset` in a test.

File: tests/integration/test_task_pool.py (hunk 4 above)
Comment (MetRonnie) [reply tests/integration/test_task_pool.py:1294]: This is because in back-compat mode the cycle point time zone is assumed to be local, whereas in normal mode it is assumed to be UTC, and this was contaminating the point parsing cache between the tests. I've opened a PR against this one that ensures the cycle point time zone is taken into account when accessing the cache: https://github.com/hjoliver/cylc-flow/pull/37

Comment (hjoliver) [reply tests/integration/test_task_pool.py:1294]: Brilliant, thanks.

File: .github/workflows/test_fast.yml [hunk 7]
```diff
@@ -20,11 +20,17 @@ jobs:
       fail-fast: false # Don't let a failed MacOS run stop the Ubuntu runs
       matrix:
         os: ['ubuntu-latest']
-        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
+        python-version: ['3.7', '3.8', '3.10', '3.11']
         include:
-          - os: 'macos-11'
-            python-version: '3.7'
+          # mac os test
+          - os: 'macos-latest'
```
Comment (MetRonnie) [inline .github/workflows/test_fast.yml:26]: I think the merge of 8.2.x into this branch wasn't quite right
```suggestion
          - os: 'macos-11'
```

File: tests/integration/test_task_pool.py [hunk 8]
```diff
@@ -1243,6 +1245,144 @@ async def test_detect_incomplete_tasks(
...
+    id_ = flow({
+        'scheduler': {
+            'allow implicit tasks': 'True',
+            'cycle point format': 'CCYYMMDD',
+        },
+        'scheduling': {
+            'initial cycle point': '2001',
+            'runahead limit': rhlimit,
+            'graph': {
+                'P1D': 'a\na[+P1D] => b',
```
Comment (MetRonnie) [inline tests/integration/test_task_pool.py:1377]:
```suggestion
                'P1D': '''
                    a
                    a[+P1D] => b
                ''',
```

File: tests/integration/test_task_pool.py [hunk 9]
```diff
@@ -1243,6 +1245,144 @@ async def test_detect_incomplete_tasks(
...
+            },
+        }
+    })
+    schd = scheduler(id_,)
+    async with start(schd):
```
Comment (MetRonnie) [inline tests/integration/test_task_pool.py:1382]: Might be useful to do this so that if the test fails, we can see what runahead debug log messages were produced

```suggestion
    async with start(schd, level=logging.DEBUG):
```

**Review by wxtim — COMMENTED** [review]
Review so far...

- [x] Wrote simple examples to check that both bugs were fixed.
- [x] Read the code.
- [x] Checked that the tests covered the two bug cases.

File: tests/integration/test_task_pool.py [hunk 10]
```diff
@@ -1243,6 +1245,147 @@ async def test_detect_incomplete_tasks(
...
+            'scheduling': {
+                'initial cycle point': '1',
+                'cycling mode': 'integer',
+                'runahead limit': 'P3',
+                'graph': {
+                    'P1': 'a'
+                },
+            }
+        }
+        point = lambda point: IntegerPoint(str(int(point)))
```
Comment (wxtim) [inline tests/integration/test_task_pool.py:1288]: [Flake8:E371](https://www.flake8rules.com/rules/E731.html) is not happy with this. I'm not sure how important it is in this context, but consider...
```suggestion
        def(point):
            return IntegerPoint(str(int(point)))
```

Comment (oliver-sanders) [reply tests/integration/test_task_pool.py:1288]: Flake8 won't be happy with that inline function either.

IMO it's ok, especially for a test.

Comment (hjoliver) [reply tests/integration/test_task_pool.py:1291]: I'll leave it as-is then.

**Comment by hjoliver** [comment]
@wxtim - did you intend to push the commit "wip" 238a79037365815432906e8f1f8a2781204fd02d to this branch? It isn't obviously related, and it's causing a couple of test failures.

**Comment by wxtim** [comment]
No, that's a mistake. I'm surprised I managed that but it doesn't belong here. Thats unrelated. Sorry. 😢

File: tests/integration/test_task_pool.py (hunk 10 above)
Comment (wxtim) [reply tests/integration/test_task_pool.py:1291]: > Flake8 won't be happy with that inline function either.

You sure?

```console
> echo 'def point(point): return 42'> foo.py
> flake8 foo.py
...
```

**Review by oliver-sanders — APPROVED** [review]
