### PR TITLE
fix.lint.U013 incomplete message

### LINKED ISSUE #6205: cylc lint and CYLC_SUITE_DEF_PATH variable (rule U013) message is not complete
### Description

Cylc lint, running on a variable `CYLC_SUITE_DEF_PATH` does not provide a properly resolved explanation of the linting failure, `[U013] flow.cylc:3: Obsolete environment variables: {vars}`. If the variable is, for example, `CYLC_SUITE_NAME`, then it will provide a useful message, `[U012] flow.cylc:3: Deprecated environment variables: ['CYLC_SUITE_NAME: CYLC_WORKFLOW_ID']`.

NOTE: Using `cylc-flow=8.3.0`

### Reproducible Example

flow.cylc: 

```
[runtime]
    [[root]]
        script = echo $CYLC_SUITE_DEF_PATH
```

```
$ cylc lint
[U013] flow.cylc:3: Obsolete environment variables: {vars}

Checked /tmp/basic-workflow against ['728', 'style'] rules and found 1 issue.
```

### Expected Behaviour

`{vars}` should say what the variable is (and if possible, a suitable alternative if one exists).

### PR DESCRIPTION
**Pull request by wxtim**
closes #6205 

**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` (and `conda-environment.yml` if present).
- [x] Tests are included (or explain why tests are not needed).
- [x] `CHANGES.md` entry included if this is a change that can affect users
- [x] [Cylc-Doc](https://github.com/cylc/cylc-doc) pull request opened if required at cylc/cylc-doc/pull/XXXX.
- [x] If this is a bug fix, PR should be raised against the relevant `?.?.x` branch.

### CODE REVIEW

File: changes.d/6178.fix.md
Comment (wxtim) [inline changes.d/6178.fix.md:1]: The arbitrary slug rears its ugly head again. Least it's not me this time.

**Review by MetRonnie — COMMENTED** [review]
There's a similar issue for https://github.com/cylc/cylc-flow/blob/75d144e3449d12adda1fbd3bcb23f5c42c12be2b/cylc/flow/scripts/lint.py#L679-L694
```
expired handlers = %(suite_uuid)s %(user@host)s
```

File: changes.d/6178.fix.md
Comment (MetRonnie) [reply changes.d/6178.fix.md:1]: Not sure why there is no conflict, but I think you should drop this change as the fragment has been deleted on 8.3.x

**Comment by wxtim** [comment]
> There's a similar issue for 

Re-drafted - I'm going to write an automated test for this.

File: tests/unit/scripts/test_lint_checkers.py
Comment (wxtim) [inline tests/unit/scripts/test_lint_checkers.py:1]: This is Separate - I have in my mind that at some point I'm going to refactor out those aspects of Cylc lint which are data rather than infrastructure.

File: cylc/flow/scripts/lint.py [hunk 1]
```diff
@@ -370,7 +380,12 @@ def check_indentation(line: str) -> bool:
 
 
 def check_lowercase_family_names(line: str) -> bool:
-    """Check for lowercase in family names."""
+    """Check for lowercase in family names.
+
+    Examples:
+        >>> check_lowercase_family_names(' inherit = FOO')
+        False
```
Comment (MetRonnie) [inline cylc/flow/scripts/lint.py:387]: Why only add this negative test case?

File: tests/unit/scripts/test_lint_checkers.py [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+def test_custom_checker_doctests(ref, check):
+    """All check functions have at least one failure doctest
+
+    By forcing each check function to have valid doctests
+    for the case that linting has failed we are able to
+    check that the function outputs the correct information
+    for formatting the short formats.
+
+    ref is useful to allow us to identify the check, even
+    though not used in the test.
```
Comment (MetRonnie) [inline tests/unit/scripts/test_lint_checkers.py:56]: Can use the `id` arg of `pytest.param` for this


```suggestion
    'check',
    # Those checks that have custom checker functions
    # and a short message with variables to insert:
    [
        pytest.param(c, id=c.get('function').__name__) for _, c in ALL_CHECKS
        if c.get('function') in CHECKERS
    ]
)
def test_custom_checker_doctests(check):
    """All check functions have at least one failure doctest

    By forcing each check function to have valid doctests
    for the case that linting has failed we are able to
    check that the function outputs the correct information
    for formatting the short formats.
```

File: cylc/flow/scripts/lint.py (hunk 1 above)
Comment (wxtim) [reply cylc/flow/scripts/lint.py:387]:
```suggestion
    Examples:
        >>> check_lowercase_family_names(' inherit = FOO')
        False
        >>> check_lowercase_family_names(' inherit = foo')
        True
```

**Comment by MetRonnie** [comment]
> There's a similar issue for
> 
> https://github.com/cylc/cylc-flow/blob/75d144e3449d12adda1fbd3bcb23f5c42c12be2b/cylc/flow/scripts/lint.py#L679-L694
> 
> ```
> expired handlers = %(suite_uuid)s %(user@host)s
> ```

This still hasn't been addressed

File: cylc/flow/scripts/lint.py [hunk 3]
```diff
@@ -673,7 +687,7 @@ def list_wrapper(line: str, check: Callable) -> Optional[Dict[str, str]]:
     },
     'U015': {
         'short': (
-            'Deprecated template variables.'),
+            'Deprecated template variables: {suggest}'),
```
Comment (MetRonnie) [inline cylc/flow/scripts/lint.py:690]: Rather than have to rely on variable names matching here (`suggest` in this case but `vars` elsewhere), why not just make the check functions return a list of strings, and add the joined list to the end of the `short` message?

Comment (wxtim) [reply cylc/flow/scripts/lint.py:690]: Allows us to insert multiple variables 

```
msg = check_meta['short'].format(**check)
```

Comment (wxtim) [reply cylc/flow/scripts/lint.py:690]: Un drafted - I think that my long term goal is to have a better defined check API so that others can add them, but I think I want this fixed sooner, and will worry about that later.

File: changes.d/6214.fix.md [hunk 4]
```diff
@@ -0,0 +1 @@
+Cylc lint U013 Now tells you which deprecated variable you used
```
Comment (MetRonnie) [inline changes.d/6214.fix.md:1]:
```suggestion
`cylc lint` rule U013 now tells you which deprecated variables you used
```

File: tests/unit/scripts/test_lint_checkers.py [hunk 5]
```diff
@@ -0,0 +1,93 @@
...
+from cylc.flow.scripts import lint
+
+VARS = re.compile(r'\{(.*)\}')
+
+# Functions in Cylc Lint defined with "check_*
+CHECKERS = [
+    getattr(lint, i) for i in lint.__dir__() if i.startswith('check_')]
+# List of checks defined as checks by Cylc Lint
+ALL_CHECKS = list(
+    lint.MANUAL_DEPRECATIONS.items()) + list(lint.STYLE_CHECKS.items())
```
Comment (MetRonnie) [inline tests/unit/scripts/test_lint_checkers.py:33]:
```suggestion
ALL_CHECKS = [
    *lint.MANUAL_DEPRECATIONS.values(),
    *lint.STYLE_CHECKS.values(),
]
```

File: tests/unit/scripts/test_lint_checkers.py [hunk 6]
```diff
@@ -0,0 +1,93 @@
...
+
+finder = doctest.DocTestFinder()
+
+
+@pytest.mark.parametrize(
+    'check',
+    # Those checks that have custom checker functions
+    # and a short message with variables to insert:
+    [
+        pytest.param(c, id=c.get('function').__name__) for _, c in ALL_CHECKS
```
Comment (MetRonnie) [inline tests/unit/scripts/test_lint_checkers.py:43]:
```suggestion
        pytest.param(c, id=c.get('function').__name__) for c in ALL_CHECKS
```

File: tests/unit/scripts/test_lint_checkers.py [hunk 7]
```diff
@@ -0,0 +1,93 @@
...
+
+
+@pytest.mark.parametrize(
+    'ref, check',
+    # Those checks that have custom checker functions
+    # and a short message with variables to insert:
+    [
+        (c[1].get('function'), c[1]) for c in ALL_CHECKS
+        if c[1].get('function') in CHECKERS
+        and VARS.findall(c[1]['short'])
```
Comment (MetRonnie) [inline tests/unit/scripts/test_lint_checkers.py:68]:
```suggestion
        (c.get('function'), c) for c in ALL_CHECKS
        if c.get('function') in CHECKERS
        and VARS.findall(c['short'])
```

**Review by MetRonnie — APPROVED** [review]
Some minor suggestions

**Review by MetRonnie — APPROVED** [review]
