### PR TITLE
Remove job-init-env.sh support.

### LINKED ISSUE #3376: job environment init
All suite-running functional tests are now failing in my Python venv cylc-flow environment. Pretty sure they used to work, and I'm not sure what I've change d recently, but the problem is that suite jobs in the test battery (as executed by `./etc/bin/run-functional-tests.sh`) do not have access to the venv cylc library (if I just run a suite from within the venv, jobs do work). So:

1. I tried using a `flow-tests.rc` to configure to activate then environment
    - hence: #3375 

2. I (and our docs) are confused about `global init-script` and `job-init-env.sh` for Cylc 8
    - topic of this issue

## User Guide

The only references to `job-init-env.sh` are:

1. Under "Task Job Access to Cylc":
> (login shell etc...)
> To customize the environment more generally for Cylc on jobs hosts, use ``job-init-env.sh``.

2. Under "Installation"
> Your site administrator may customise the environment for all task jobs by adding a site ``job-init-env.sh`` file and populate it with appropriate contents. If customisation is still required, you can add your own ``${HOME}/.cylc/job-init-env.sh`` file and populate it with the
appropriate contents.

The `global init-script` item is also mentioned, just once (in the global config reference):
> If specified, the value of this setting will be inserted to just before the ``init-script`` section of all job scripts that are to be submitted to the specified remote host.

Under suite config reference, for `init-script` it says:
> The original intention for this item was to allow remote tasks to source login scripts to configure their access to cylc, but this should no longer be necessary (see :ref:`HowTasksGetAccessToCylc`).

(where the ref suggests use `job-init-env.sh` as above)

## cylc-flow code

The only reference to `job-init-env.sh` is in `etc/job.sh`:
```bash
    typeset JOB_INIT_ENV=
    # conf/job-init-env.sh for back-compat pre 7.7.0.
    JOB_INIT_ENV="${HOME}/.cylc/job-init-env.sh"
    if [[ -f "${JOB_INIT_ENV}" ]]; then
        if "${CYLC_DEBUG:-false}"; then
            . "${JOB_INIT_ENV}"
        else
            . "${JOB_INIT_ENV}" 1>'/dev/null' 2>&1
        fi
    fi
    # Init-Script
    cylc__job__run_inst_func 'global_init_script'
    cylc__job__run_inst_func 'init_script'
```
Clearly only a **user** `job-init-env.sh` is sourced here (no site one), just before `global init-script`. And what's that back-compat comment: does it imply job-init-env itself is only retained here for back compat with cylc-7, or does the comment just need to be deleted because it refers to some now-deleted back-compat code.

### PR DESCRIPTION
**Pull request by hjoliver**
These changes close #3376
- remove support for sourcing user `job-init-env.sh` in task job scripts
  - (site `job-init-env.sh` already removed during CYLC_DIR removal for Cylc 8)
- I have retained support for `init-script` because it provides some additional flexibility (e.g.: can be configured centrally on the suite host, rather than by modifying login scripts on all job hosts) but documented that use of login scripts is preferred

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).

- [x] Does not need tests (code deletion only).

- [x] Appropriate change log entry included.

- [x] (master branch) I have opened a documentation PR at cylc/cylc-doc/pull/82

### CODE REVIEW

File: cylc/flow/etc/job.sh [hunk 1]
```diff
@@ -36,16 +36,6 @@ cylc__job__main() {
         set -x
     fi
     # Prelude
```
Comment (matthewrmshin) [inline cylc/flow/etc/job.sh]: Can remove the `# Prelude` comment line as well.

Comment (hjoliver) [reply cylc/flow/etc/job.sh]: Done.

**Comment by hjoliver** [comment]
(One review will do for this).
