### PR TITLE
fix reload failures on active/incomplete orphans

### LINKED ISSUE #6814: set non-existent task while reloading causes crash
### Description

Version: 8.4.0

```
2025-06-24T23:32:55Z INFO - LOADING job data
2025-06-24T23:33:01Z INFO - Reload completed.
2025-06-24T23:33:02Z INFO - RESUMING the workflow now
2025-06-24T23:33:02Z INFO - Command "reload_workflow" actioned. ID=6f53dee1-09da-4e5b-b9c0-d652b7ed35f3
2025-06-24T23:33:02Z INFO - [20250624T1200Z/bop_ocean_nzcsm_sftp_upload/01:failed] => succeeded
2025-06-24T23:33:03Z INFO - Command "set" actioned. ID=f3e6942b-bb5c-49cb-8c88-f1429893a85f
2025-06-24T23:33:03Z INFO - Broadcast set:
    + [20250624T2250Z/himawari_sftp_upload] [environment]poll_himawari_netcdf_1000_workflow=himawari/run1
    + [20250624T2250Z/himawari_sftp_upload] [environment]poll_himawari_netcdf_1000_task=res_1000
    + [20250624T2250Z/himawari_sftp_upload] [environment]poll_himawari_netcdf_1000_point=20250624T2250Z
    + [20250624T2250Z/himawari_sftp_upload] [environment]poll_himawari_netcdf_1000_cylc_run_dir=/niwa/oper/ecox_oper/cylc-run
    + [20250624T2250Z/himawari_sftp_upload] [environment]poll_himawari_netcdf_1000_status=succeeded
2025-06-24T23:33:03Z CRITICAL - An uncaught error caused Cylc to shut down.
    If you think this was an issue in Cylc, please report the following traceback to the developers.
    https://github.com/cylc/cylc-flow/issues/new?assignees=&labels=bug&template=bug.md&title=;
2025-06-24T23:33:03Z ERROR - 'bop_ocean_nzcsm_sftp_upload'
    Traceback (most recent call last):
      File "/opt/niwa/share/cylc/8.4.0/lib/python3.9/site-packages/cylc/flow/scheduler_cli.py", line 695, in cylc_play
        asyncio.get_running_loop()
    RuntimeError: no running event loop
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "/opt/niwa/share/cylc/8.4.0/lib/python3.9/site-packages/cylc/flow/scheduler.py", line 707, in run_scheduler
        await self._main_loop()
      File "/opt/niwa/share/cylc/8.4.0/lib/python3.9/site-packages/cylc/flow/scheduler.py", line 1773, in _main_loop
        self.xtrigger_mgr.call_xtriggers_async(itask)
      File "/opt/niwa/share/cylc/8.4.0/lib/python3.9/site-packages/cylc/flow/xtrigger_mgr.py", line 696, in call_xtriggers_async
        self.broadcast_mgr.put_broadcast(
      File "/opt/niwa/share/cylc/8.4.0/lib/python3.9/site-packages/cylc/flow/broadcast_mgr.py", line 332, in put_broadcast
        self.data_store_mgr.delta_broadcast()
      File "/opt/niwa/share/cylc/8.4.0/lib/python3.9/site-packages/cylc/flow/data_store_mgr.py", line 2233, in delta_broadcast
        self._generate_broadcast_node_deltas(
      File "/opt/niwa/share/cylc/8.4.0/lib/python3.9/site-packages/cylc/flow/data_store_mgr.py", line 2261, in _generate_broadcast_node_deltas
        cfg['runtime'][node.name]
      File "/opt/niwa/share/cylc/8.4.0/lib/python3.9/site-packages/cylc/flow/parsec/OrderedDict.py", line 38, in __getitem__
        return OrderedDict.__getitem__(self, key)
    KeyError: 'bop_ocean_nzcsm_sftp_upload'
2025-06-24T23:33:03Z CRITICAL - Workflow shutting down - 'bop_ocean_nzcsm_sftp_upload'
2025-06-24T23:33:03Z WARNING - Orphaned tasks:
    * 20250624T1200Z/ecmwf_sftp_ifs_upload (running)
    * 20250624T1200Z/geotiff_gis_nzcsm_very_low_cloud (running)
    * 20250624T1800Z/bop_nzlam_sftp_upload (running)
    * 20250624T2230Z/gsmapnow_netcdf (submitted)
2025-06-24T23:33:03Z WARNING - 20250624T1200Z/bop_ocean_nzcsm_sftp_upload/01: incomplete task event handler ('event-handler-00', 'succeeded')
2025-06-24T23:33:04Z INFO - DONE
```
Looks like the reason is the xtrigger satisfaction of a removed task, relating to this section in the xtrigger manager:
```
            # General case: potentially slow asynchronous function call.
            if sig in self.sat_xtrig:
                # Already satisfied, just update the task
                if not itask.state.xtriggers[label]:
                    itask.state.xtriggers[label] = True
                    res = {}
                    for key, val in self.sat_xtrig[sig].items():
                        res["%s_%s" % (label, key)] = val
                    if res:
                        xtrigger_env = [{'environment': {key: str(val)}} for
                                        key, val in res.items()]
                        self.broadcast_mgr.put_broadcast(
                            [str(itask.point)],
                            [itask.tdef.name],
                            xtrigger_env
                        )
                    if self.all_task_seq_xtriggers_satisfied(itask):
                        self.sequential_spawn_next.add(itask.identity)
                continue
```
(`put_broadcast` creates a delta which searches for a non-existent cfg item)
pretty hard to reproduce

### Reproducible Example

Test in [fix](https://github.com/cylc/cylc-flow/pull/6817) replicated this bug

### Expected Behaviour

no crash

### LINKED ISSUE #6815: reload fail on xtrigger removal
### Description
On removal of xtrigger, reload fails resulting in a partially populated pool:
```
2025-06-25T03:52:13Z INFO - Reloading task definitions.
2025-06-25T03:52:13Z WARNING - [20250625T0000Z/bar/01:failed] will not spawn children - task definition removed
2025-06-25T03:52:13Z INFO - [20250626T0000Z/foo:waiting(queued)] reloaded task definition
2025-06-25T03:52:13Z ERROR - Traceback (most recent call last):
      File "/home/sutherlander/cylc/cylc-flow/cylc/flow/scheduler_cli.py", line 696, in cylc_play
        asyncio.get_running_loop()
    RuntimeError: no running event loop
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "/home/sutherlander/cylc/cylc-flow/cylc/flow/scheduler.py", line 1026, in process_command_queue
        n_warnings = await cmd.__anext__()
      File "/home/sutherlander/cylc/cylc-flow/cylc/flow/commands.py", line 420, in reload_workflow
        schd.pool.reload(config)
      File "/home/sutherlander/cylc/cylc-flow/cylc/flow/task_pool.py", line 1050, in reload
        self._reload_taskdefs()
      File "/home/sutherlander/cylc/cylc-flow/cylc/flow/task_pool.py", line 1142, in _reload_taskdefs
        self.create_data_store_elements(itask)
      File "/home/sutherlander/cylc/cylc-flow/cylc/flow/task_pool.py", line 252, in create_data_store_elements
        self.data_store_mgr.increment_graph_window(
      File "/home/sutherlander/cylc/cylc-flow/cylc/flow/data_store_mgr.py", line 811, in increment_graph_window
        self.generate_ghost_task(
      File "/home/sutherlander/cylc/cylc-flow/cylc/flow/data_store_mgr.py", line 1297, in generate_ghost_task
        self._process_internal_task_proxy(itask, tproxy)
      File "/home/sutherlander/cylc/cylc-flow/cylc/flow/data_store_mgr.py", line 1550, in _process_internal_task_proxy
        sig = self.schd.xtrigger_mgr.get_xtrig_ctx(
      File "/home/sutherlander/cylc/cylc-flow/cylc/flow/xtrigger_mgr.py", line 626, in get_xtrig_ctx
        ctx = deepcopy(self.xtriggers.functx_map[label])
    KeyError: 'wall_clock'
2025-06-25T03:52:13Z ERROR - Command "reload_workflow" failed. ID=41329dc8-0c35-49d3-8125-feb63f7ec2dc
    'wall_clock'
```

### Reproducible Example
Run the following workflow:
`$ cylc vip <workflow>`
```
[scheduling]
    initial cycle point = 20250625T00
    [[graph]]
        PT12H = """
foo[-PT12H] => foo => bar
@wall_clock => bar
"""
[runtime]
    [[foo]]
        script = sleep 5
    [[bar]]
        script = false
```
Remove `bar` from the definition:
```
[scheduling]
    initial cycle point = 20250625T00
    [[graph]]
        PT12H = """
foo[-PT12H] => foo
"""
[runtime]
    [[foo]]
        script = sleep 5
```
reinstall/reload the workflow:
`$ cylc vr <workflow>/run1`

### Expected Behaviour

Workflow reloaded successfully

### PR DESCRIPTION
**Pull request by dwsutherland**
closes #6814
closes #6815

Note - A good way to see the bugs is to comment out a fix and run the test for each.

**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` (and `conda-environment.yml` if present).
- [x] Tests are included (or explain why tests are not needed).
- [x] Changelog entry included if this is a change that can affect users
- [x] [Cylc-Doc](https://github.com/cylc/cylc-doc) pull request opened if required at cylc/cylc-doc/pull/XXXX.
- [x] If this is a bug fix, PR should be raised against the relevant `?.?.x` branch.

### CODE REVIEW

File: changes.d/6817.fix.md [hunk 1]
```diff
@@ -0,0 +1 @@
+Fixes reload failures about orphaned tasks.
```
Comment (wxtim) [inline changes.d/6817.fix.md]: Cryptic IMO
```suggestion
Fixes a bug where reload removed information about orphaned tasks from the data store.
```

File: tests/integration/test_reload.py [hunk 2]
```diff
@@ -146,3 +146,71 @@ async def test_reload_failure(
...
         assert schd.config.cfg['scheduling']['graph']['R1'] == 'one'
+
+
+async def test_orphan_reload(
+    flow,
+    scheduler,
+    start,
+    log_filter,
+):
+    """Reload should not fail about orphaned tasks.
```
Comment (wxtim) [inline tests/integration/test_reload.py]:
```suggestion
    """Reload should not remove orphaned task data.
```

File: tests/integration/test_reload.py [hunk 3]
```diff
@@ -146,3 +146,71 @@ async def test_reload_failure(
...
+
+    The following aspects of reload about orphans are tested:
+        - Removal of both xtrigger and associated active/incomplete task.
+        - Broadcast deltas generated after reload.
```
Comment (wxtim) [inline tests/integration/test_reload.py]: Check that I have the issue mapping the right way around!
```suggestion
        - Removal of both xtrigger and associated active/incomplete task.
          https://github.com/cylc/cylc-flow/issues/6814
        - Broadcast deltas generated after reload.
          https://github.com/cylc/cylc-flow/issues/6815
```

File: tests/integration/test_reload.py [hunk 4]
```diff
@@ -146,3 +146,71 @@ async def test_reload_failure(
...
+    """
+    before = {
+        'scheduler': {
+            'allow implicit tasks': True
+        },
```
Comment (wxtim) [inline tests/integration/test_reload.py]: Not required: The fixture adds this as a default. 😄 
```suggestion
```

File: tests/integration/test_reload.py [hunk 5]
```diff
@@ -146,3 +146,71 @@ async def test_reload_failure(
...
+                    foo => bar
+                    @wall_clock => bar
+                '''
+            }
+        }
+    }
+    after = {
+        'scheduler': {
+            'allow implicit tasks': True
+        },
```
Comment (wxtim) [inline tests/integration/test_reload.py]:
```suggestion
```

File: changes.d/6817.fix.md (hunk 1 above)
Comment (MetRonnie) [reply changes.d/6817.fix.md]: Even simpler:
```suggestion
Fixes a couple of rare scheduler crashes.
```

File: tests/integration/test_reload.py (hunk 3 above)
Comment (MetRonnie) [reply tests/integration/test_reload.py]: I think it's the other way round

File: tests/integration/test_reload.py [hunk 6]
```diff
@@ -146,3 +146,71 @@ async def test_reload_failure(
...
+            'graph': {
+                'R1': 'foo'
+            }
+        }
+    }
+    id_ = flow(before)
+    schd = scheduler(id_)
+    async with start(schd):
+        # spawn in bar
+        foo = schd.pool.get_tasks()[0]
```
Comment (MetRonnie) [inline tests/integration/test_reload.py]: For clarity:
```suggestion
        foo = schd.pool._get_task_by_id('20010101T0000Z/foo')
```

File: tests/integration/test_reload.py [hunk 7]
```diff
@@ -146,3 +146,71 @@ async def test_reload_failure(
...
+        schd.pool.task_events_mgr.process_message(
+            foo, '20010101T0000Z', 'succeeded')
+        bar = schd.pool.get_tasks()[0]
+        assert bar.identity == '20010101T0000Z/bar'
```
Comment (MetRonnie) [inline tests/integration/test_reload.py]:
```suggestion
        bar = schd.pool._get_task_by_id('20010101T0000Z/bar')
```

File: tests/integration/test_reload.py [hunk 8]
```diff
@@ -146,3 +146,71 @@ async def test_reload_failure(
...
+            }
+        }
+    }
+    id_ = flow(before)
+    schd = scheduler(id_)
+    async with start(schd):
+        # spawn in bar
+        foo = schd.pool.get_tasks()[0]
+        schd.pool.task_events_mgr.process_message(
+            foo, '20010101T0000Z', 'succeeded')
```
Comment (MetRonnie) [inline tests/integration/test_reload.py]: The 2nd arg is severity, not cycle point
```suggestion
        schd.pool.task_events_mgr.process_message(foo, 'INFO', 'succeeded')
```

File: tests/integration/test_reload.py [hunk 9]
```diff
@@ -146,3 +146,71 @@ async def test_reload_failure(
...
+        bar = schd.pool.get_tasks()[0]
+        assert bar.identity == '20010101T0000Z/bar'
+        # set bar to failed
+        schd.pool.task_events_mgr.process_message(
+            bar, '20010101T0000Z', 'failed')
```
Comment (MetRonnie) [inline tests/integration/test_reload.py]:
```suggestion
        schd.pool.task_events_mgr.process_message(bar, 'INFO', 'failed')
```

File: changes.d/6817.fix.md (hunk 1 above)
Comment (hjoliver) [reply changes.d/6817.fix.md]: IMO we should at least hint at what triggers the bug. How about this?

```suggestion
Fixes two rare bugs associated with reloading the workflow configuration
after removing tasks or xtriggers from it.

File: tests/integration/test_reload.py [hunk 10]
```diff
@@ -146,3 +146,71 @@ async def test_reload_failure(
...
+
+async def test_orphan_reload(
+    flow,
+    scheduler,
+    start,
+    log_filter,
+):
+    """Reload should not fail about orphaned tasks.
+
+    The following aspects of reload about orphans are tested:
```
Comment (hjoliver) [inline tests/integration/test_reload.py]: Can "reload about orphans" be rephrased more clearly? "reload after removing tasks from the workflow config" maybe?

File: tests/integration/test_reload.py (hunk 2 above)
Comment (MetRonnie) [reply tests/integration/test_reload.py]: The bug was not data being removed, it was the scheduler crashing

**Comment by oliver-sanders** [comment]
(assigned commenters as reviewers)

File: tests/integration/test_reload.py (hunk 10 above)
Comment (dwsutherland) [reply tests/integration/test_reload.py]: Well the reason why I use orphan, is because it's only running/incomplete tasks that are stick about (are orphaned) after removal from the workflow config and reload..

File: cylc/flow/data_store_mgr.py [hunk 11]
```diff
@@ -1658,13 +1733,9 @@ def insert_job(
...
         # so use task cfg as base.
-        j_cfg = pdeepcopy(self._apply_broadcasts_to_runtime(
-            tp_tokens,
-            self.schd.config.cfg['runtime'][tproxy.name]
-        ))
-        for key, val in job_conf.items():
-            j_cfg[key] = val
-        j_buf.runtime.CopyFrom(runtime_from_config(j_cfg))
+        j_buf.runtime.CopyFrom(
+            runtime_from_partial(job_conf, tproxy.runtime)
```
Comment (dwsutherland) [inline cylc/flow/data_store_mgr.py:1729]: Used instead, because it can pick up existing orphan runtime, or runtime of newly created post reload.

Comment (dwsutherland) [reply cylc/flow/data_store_mgr.py:1729]: Note: this is covered by `insert_job` testing of `tests/i/test_data_store_mgr.py`.

File: cylc/flow/data_store_mgr.py [hunk 12]
```diff
@@ -214,6 +214,38 @@
     WORKFLOW: {'log_records': 10}
 }
 
+# internal runtime to protobuf field name mapping
+RUNTIME_MAPPING = {
```
Comment (MetRonnie) [inline cylc/flow/data_store_mgr.py]: Duplicates https://github.com/cylc/cylc-flow/blob/2e6f5414c7c021846277170d870b21db1582c468/cylc/flow/network/schema.py#L876-L889

File: cylc/flow/data_store_mgr.py [hunk 13]
```diff
@@ -318,6 +350,47 @@ def runtime_from_config(rtconfig):
...
+        elif key in RUNTIME_TRY_ITEMS:
+            try:
+                setattr(
+                    runtime,
+                    RUNTIME_MAPPING[key],
+                    val[RUNTIME_TRY_ITEMS[key]]
+                )
+            except (KeyError, TypeError):
+                with suppress(KeyError, TypeError):
+                    setattr(runtime, RUNTIME_MAPPING[key], val)
```
Comment (MetRonnie) [inline cylc/flow/data_store_mgr.py]: I'm not sure of the need for this, seems overly-cautious at the cost of readability to me 
```suggestion
        elif key == 'platform':
            setattr(runtime, RUNTIME_MAPPING[key], val['name'])
```

File: tests/integration/test_reload.py (hunk 10 above)
Comment (hjoliver) [reply tests/integration/test_reload.py]: Understood, but I don't understand the phrase "reload about orphans". (About??).

Comment (hjoliver) [reply tests/integration/test_reload.py]: Do  you mean "because of"?

File: cylc/flow/data_store_mgr.py (hunk 13 above)
Comment (dwsutherland) [reply cylc/flow/data_store_mgr.py]: That won't work, there are scenarios where `name` doesn't exist in `platform` and where `platform` doesn't exist..
The `runtime_from_config` has :
```
    try:
        platform = rtconfig['platform']['name']
    except (KeyError, TypeError):
        platform = rtconfig['platform']
  ```
  
 However this is passed in as an kwarg to `Runtime` .. Which can handle `None`s

File: tests/integration/test_reload.py (hunk 10 above)
Comment (dwsutherland) [reply tests/integration/test_reload.py]: "because of specific types or aspects of orphans"?  not all orphans will produce the bug

File: cylc/flow/data_store_mgr.py (hunk 12 above)
Comment (dwsutherland) [reply cylc/flow/data_store_mgr.py]: That one is the inverse  `Pb -> cfg`, I made `cfg -> Pb` .. I can construct one from the other.. But for fast key lookups I want to map from rtconfig to Pb by iterating on rtconfig (which may be smaller)..

File: tests/integration/test_reload.py (hunk 10 above)
Comment (dwsutherland) [reply tests/integration/test_reload.py]: Ok fixed.

File: cylc/flow/data_store_mgr.py (hunk 12 above)
Comment (dwsutherland) [reply cylc/flow/data_store_mgr.py]: Schema `Pb -> cfg` is now generated from the `data_store_mgr` one (can't do the reverse, circular import).. The GQL needs to match the Pb fields (as Pb is the backing data), so this is fine.

File: cylc/flow/data_store_mgr.py (hunk 13 above)
Comment (dwsutherland) [reply cylc/flow/data_store_mgr.py]: I've simplified this now.. Sometimes `val` is a dict that doesn't contain `name` so ignore the exception, otherwise `val` is a string so can use the `else` (at the end)

File: cylc/flow/data_store_mgr.py [hunk 14]
```diff
@@ -214,6 +214,37 @@
...
+    'outputs': 'outputs',
+    'post-script': 'post_script',
+    'platform': 'platform',
+    'pre-script': 'pre_script',
+    'run mode': 'run_mode',
+    'script': 'script',
+    'submission polling intervals': 'submission_polling_intervals',
+    'submission retry delays': 'submission_retry_delays',
+    'work sub-directory': 'work_sub_dir',
+}
```
Comment (hjoliver) [inline cylc/flow/data_store_mgr.py:238]: Can we generate this automatically (` ` and `-` --> `_`) so that it just works if new runtime config items are added - or is there a good reason for listing each one explicitly like this?

File: cylc/flow/network/schema.py [hunk 15]
```diff
@@ -874,19 +875,10 @@ class Meta:
...
-    'err_script': 'err-script',
-    'exit_script': 'exit-script',
-    'pre_script': 'pre-script',
-    'post_script': 'post-script',
-    'work_sub_dir': 'work sub-directory',
+    v: k
+    for k, v in RUNTIME_CFG_MAP_TO_FIELD.items()
 }
-"""Map GQL Runtime fields' names to workflow config setting names."""
+"""Map Pb/GQL Runtime fields' names to workflow config setting names."""
```
Comment (hjoliver) [inline cylc/flow/network/schema.py]: Minor, but we should use "GraphQL" not "GQL" (there are several other instances in this file). For one thing, grepping for GraphQL will miss this comment, and for another thing "GQL" is a something entirely different.

https://en.m.wikipedia.org/wiki/Graph_Query_Language

File: cylc/flow/data_store_mgr.py [hunk 16]
```diff
@@ -318,6 +349,40 @@ def runtime_from_config(rtconfig):
     )
 
 
+def runtime_from_partial(rtconfig, runtimeold=None):
+    """Populate runtime object from partial/full config.
+
+    Potentially slower with all the setattr calls, but no expected fields.
```
Comment (hjoliver) [inline cylc/flow/data_store_mgr.py]: Potentially slower than what - the non-partial one?

**Review by hjoliver — COMMENTED** [review]
(Partially reviewed)

File: changes.d/6817.fix.md [hunk 17]
```diff
@@ -0,0 +1,2 @@
+Fixes two rare bugs associated with reloading the workflow configuration
+after removing tasks or xtriggers from it.
```
Comment (wxtim) [inline changes.d/6817.fix.md]:
```suggestion
after removing tasks or xtriggers.
```

File: cylc/flow/data_store_mgr.py (hunk 14 above)
Comment (wxtim) [reply cylc/flow/data_store_mgr.py:238]:
```python
from cylc.flow.cfgspec import SPEC
{
    i[1].display_name: re.sub('[\s-]', '_', i[1].display_name)
    for i in SPEC.get('runtime', '<namespace>').walk(1)
    if i[0] != 0
}
```

TBH this feels like something that should be implemented in the Parsec Layer - i.e.

```python

    def get_pythonsafe_mapping(self, *address) -> dict[str, str]:
        """Get a mapping of spec names with spaces and `-` replaced by underscores."""
        return {
            i[1].display_name: re.sub('[\s-]', '_', i[1].display_name)
            for i in self.SPEC.get('runtime', '<namespace>').walk(1)
            if i[0] != 0
        }

```

Comment (dwsutherland) [reply cylc/flow/data_store_mgr.py:238]: Only really this one `'work sub-directory': 'work_sub_dir',` bucks the trend.... It was partially auto-generated when the inverse was set in the  `schema` ..

However, `data_messages.proto` is manually set anyways.

Comment (hjoliver) [reply cylc/flow/data_store_mgr.py:238]: OK, not worth refactoring that I guess.

File: changes.d/6817.fix.md (hunk 17 above)
Comment (dwsutherland) [reply changes.d/6817.fix.md]: Apologies, English is my first language 🤣

**Review by wxtim — APPROVED** [review]
